name: client_customer
description: "A new Flutter project"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  flutter_dotenv: ^5.2.1
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  firebase_messaging_web: ^3.5.12
  payhere_mobilesdk_flutter: ^3.1.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  google_maps_flutter: ^2.3.0
  location_picker_flutter_map: ^1.2.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_screenutil: ^5.5.3+2

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: InterVariable
      fonts:
        - asset: fonts/Inter-VariableFont.ttf
