apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
      - name: restaurant-service
        image: tastytrail/restaurant-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: DB_URI
          value: "mongodb+srv://segroup80:se1234@cluster0.kjwdf.mongodb.net/restaurant_service"
        - name: JWT_SECRET
          value: "secret"

