apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  type: NodePort
  selector:
    app: restaurant-service
  ports:
    - port: 3012
      targetPort: 3012
      nodePort: 30504
